# schema.py

# Full database schema used for GPT prompts
DB_SCHEMA = """
CREATE TABLE leagues (
    LEAGUE_ID INT PRIMARY KEY,
    LEAGUE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE teams (
    LEAGUE_ID INT,
    TEAM_ID INT PRIMARY KEY,
    MIN_YEAR INT,
    MAX_YEAR INT,
    ABBREVIATION VARCHAR(10),
    NICKNAME VARCHAR(255) NOT NULL,
    YEARFOUNDED INT,
    CITY VARCHAR(255) NOT NULL,
    ARENA VARCHAR(255),
    ARENACAPACITY INT,
    OWNER VARCHAR(255),
    GENERALMANAGER VARCHAR(255),
    HEADCOACH VARCHAR(255),
    DLEAGUEAFFILIATION VARCHAR(255),
    FOREIGN KEY (LEAGUE_ID) REFERENCES leagues(LEAGUE_ID)
);

CREATE TABLE players (
    PLAYER_NAME VARCHAR(255) NOT NULL,
    TEAM_ID INT,
    PLAYER_ID INT PRIMARY KEY,
    SEASON INT NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID)
);

CREATE TABLE games (
    GAME_DATE_EST DATE,
    GAME_ID INT PRIMARY KEY,
    GAME_STATUS_TEXT VARCHAR(255),
    HOME_TEAM_ID INT NOT NULL,
    VISITOR_TEAM_ID INT NOT NULL,
    SEASON INT NOT NULL,
    TEAM_ID_home INT NOT NULL,
    PTS_home INT,
    FG_PCT_home DECIMAL(5, 2),
    FT_PCT_home DECIMAL(5, 2),
    FG3_PCT_home DECIMAL(5, 2),
    AST_home INT,
    REB_home INT,
    TEAM_ID_away INT,
    PTS_away INT,
    FG_PCT_away DECIMAL(5, 2),
    FT_PCT_away DECIMAL(5, 2),
    FG3_PCT_away DECIMAL(5, 2),
    AST_away INT,
    REB_away INT,
    HOME_TEAM_WINS BOOLEAN,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES teams(TEAM_ID),
    FOREIGN KEY (VISITOR_TEAM_ID) REFERENCES teams(TEAM_ID)
);

CREATE TABLE ranking (
    TEAM_ID INT,
    LEAGUE_ID INT,
    SEASON_ID INT NOT NULL,
    STANDINGSDATE DATE,
    CONFERENCE VARCHAR(255),
    TEAM VARCHAR(255) NOT NULL,
    G INT,
    W INT,
    L INT,
    W_PCT DECIMAL(5, 3),
    HOME_RECORD VARCHAR(255),
    ROAD_RECORD VARCHAR(255),
    FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID),
    FOREIGN KEY (LEAGUE_ID) REFERENCES leagues(LEAGUE_ID)
);

CREATE TABLE games_details (
    GAME_ID INT,
    TEAM_ID INT,
    TEAM_ABBREVIATION VARCHAR(10),
    TEAM_CITY VARCHAR(255),
    PLAYER_ID INT,
    PLAYER_NAME VARCHAR(255),
    NICKNAME VARCHAR(255),
    START_POSITION VARCHAR(10),
    COMMENT VARCHAR(255),
    MIN INT,
    FGM INT,
    FGA INT,
    FG_PCT DECIMAL(5, 2),
    FG3M INT,
    FG3A INT,
    FG3_PCT DECIMAL(5, 2),
    FTM INT,
    FTA INT,
    FT_PCT DECIMAL(5, 2),
    OREB INT,
    DREB INT,
    REB INT,
    AST INT,
    STL INT,
    BLK INT,
    TO INT,
    PF INT,
    PTS INT,
    PLUS_MINUS INT,
    FOREIGN KEY (GAME_ID) REFERENCES games(GAME_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES players(PLAYER_ID)
);
"""
